In [1]:
import tensorflow as tf

In [2]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [3]:
# Create an empty graph, that will be filled with operation nodes later
main_graph=tf.Graph()


# Register this graph as default graph. 
# All operations within this context will become operation nodes in this graph
with main_graph.as_default():
    
    # Create two constants of value 5
    a=tf.constant(5.0)
    b=tf.constant(5.0)
    
    # Multiply the constants with each other
    c=tf.multiply(a,b)
    

# Create a session to execute the dataflow graph
with tf.Session(graph=main_graph) as session:
    
    # Perform the calculation defined in the dataflow graph and get the result
    output=session.run(c)
    print('Result of the multiplication: %d '%output)

Result of the multiplication: 25 


In [4]:
# Create an empty graph, that will be filled with operation nodes later
main_graph=tf.Graph()

# Register this graph as default graph. 
# All operations within this context will become operation nodes in this graph
with main_graph.as_default():
    
    # Define the placeholders that will feed python arrays into the dataflow graph
    a=tf.placeholder(name='a', shape=[5], dtype=tf.float32)
    b=tf.placeholder(name='b', shape=[5], dtype=tf.float32)
    
    c=tf.multiply(a,b)
    
# Create a session to execute the dataflow graph
with tf.Session(graph=main_graph) as session:
    
    # Perform the calculation defined in the dataflow graph and get the result.
    # We must provide the values for the placeholders with "feed_dict" dictionary
    output=session.run(c, feed_dict={a: [5.0,7.0,3.0,9.0,2.0],
                                     b: [1.0,2.0,4.0,8.0,4.0],
                                     })
    print(output)

   

[ 5. 14. 12. 72.  8.]


In [5]:
# Import numpy for some array reshaping
import numpy as np

# Create an empty graph, that will be filled with operation nodes later
main_graph=tf.Graph()

# Register this graph as default graph. 
# All operations within this context will become operation nodes in this graph
with main_graph.as_default():
    # Placeholder for data input
    input_=tf.placeholder(dtype=tf.float32, shape=[1,5], name='input')
    
    ###Define the weight matrices###
    # Weight matrix, that connects the input and the 1st hidden layer
    W1=tf.get_variable(name='W1', shape=[5,10], initializer=tf.random_normal_initializer)
    # Weight matrix, that connects the 1st hidden layer and the 2nd hidden layer
    W2=tf.get_variable(name='W2', shape=[10,10], initializer=tf.random_normal_initializer)
    # Weight matrix, that connects the 2nd hidden layer and the 3rd hidden layer
    W3=tf.get_variable(name='W3', shape=[10,10], initializer=tf.random_normal_initializer)
    # Weight matrix, that connects the 3rd hidden layer and the output layer
    W4=tf.get_variable(name='W4', shape=[10,3], initializer=tf.random_normal_initializer)
         
    ####Define the forward propagation operations###
      
    #1st hidden layer
    z1=tf.matmul(input_, W1)
    a1=tf.nn.tanh(z1)
    
    #2nd hidden layer
    z2=tf.matmul(a1, W2)
    a2=tf.nn.tanh(z2)
    
    #3rd hidden layer
    z3=tf.matmul(a2, W3)
    a3=tf.nn.tanh(z3)
    
    #output layer
    z_out=tf.matmul(a3, W4)
    output=tf.nn.tanh(z_out)


# Create a session to execute the dataflow graph   
with tf.Session(graph=main_graph) as sess:
    
    # Initialize the weight matrix
    sess.run(tf.global_variables_initializer())
    
    # Define some random input
    x=np.array([1.0, 2.5, 0.7, 3.0, 9.0]).reshape([1,5])
    
    # Start the forward propagation step
    prediction=sess.run(output, feed_dict={input_: x})
    
    print('\n\n\nResult of the forward propagation: \n')
    print(prediction)




Result of the forward propagation: 

[[0.9986295 0.1366151 0.9927698]]


In [6]:
# Import numpy for some array reshaping
import numpy as np

# Create an empty graph, that will be filled with operation nodes later
main_graph=tf.Graph()

# Register this graph as default graph. 
# All operations within this context will become operation nodes in this graph
with main_graph.as_default():
    
    # Placeholder for the input data
    input_= tf.placeholder(dtype=tf.float32, shape=[1,3], name='input')
    # Placeholder for the label
    label = tf.placeholder(dtype=tf.float32, shape=[1,2], name='label')
    
    # Define a 3x2 weight matrix
    W=tf.get_variable(name='weights', shape=[3,2], dtype=tf.float32)
    
    # Compute a forward propagation step
    output=tf.nn.tanh(tf.matmul(input_, W))
    
    # Use build-in function for the mean squared error loss
    loss_op=tf.losses.mean_squared_error(labels=label, predictions=output)
    

# Create a session to execute the dataflow graph

with tf.Session(graph=main_graph) as sess:
    
    # Initialize the weight matrix
    sess.run(tf.global_variables_initializer())
    
    # Define some random input (x) and a label (y)
    # Reshape the arrays into the shape of the placeholders
    x=np.reshape([10.0,3.0,4.0], [1,3])
    y=np.reshape([5.0,2.0], [1,2])

    # Compute the prediction of the network
    nn_output=sess.run(output, feed_dict={input_: x})

    # Compute the mean squared error loss
    mse_loss=sess.run(loss_op, feed_dict={input_: x,
                                         label: y})
    print('\n\n\nOutput of the neural network: \n')
    print(nn_output)
    
    print('\nMean squared error loss: %.2f'%mse_loss)




Output of the neural network: 

[[ 0.99999946 -1.        ]]

Mean squared error loss: 12.50


In [7]:
# Import numpy for some array reshaping
import numpy as np

# Create an empty graph, that will be filled with operation nodes later
main_graph=tf.Graph()

# Register this graph as default graph. 
# All operations within this context will become operation nodes in this graph
with main_graph.as_default():
    
    # Placeholder for the input data
    input_= tf.placeholder(dtype=tf.float32, shape=[1,3], name='input')
    # Placeholder for the scalar label
    label = tf.placeholder(dtype=tf.int32, shape=[1], name='label_sparse')
    # Placeholder for the one-hot-encoded label
    label_ohe = tf.placeholder(dtype=tf.float32, shape=[1,5], name='label_one_hot_encoded')

    # Define a 3x5 weight matrix
    W=tf.get_variable(name='weights', shape=[3,5], dtype=tf.float32)
    
    # Forward propagation without an activation function
    logits=tf.matmul(input_, W)
    
    # Cross entropy loss operation, that requires the one-hot-encoded label
    loss_op=tf.nn.softmax_cross_entropy_with_logits_v2(labels=label_ohe, 
                                                       logits=logits, 
                                                       name='cross_entropy_loss')

    # Cross entropy loss operation, that requires the scalar label
    loss_op_sparse=tf.nn.sparse_softmax_cross_entropy_with_logits(labels=label, 
                                                                  logits=logits, 
                                                                  name='sparse_cross_entropy_loss')


# Create a session to execute the dataflow graph
with tf.Session(graph=main_graph) as sess:
    
    # Initialize the weight matrix
    sess.run(tf.global_variables_initializer())
    
    # Define some random input (x)
    x=np.reshape([10.0,3.0,4.0], [1,3])
    
    # Define the scalar label 
    y=np.reshape([2], [1])
    # The same label but one-hot-encoded version of it
    y_ohe=np.reshape([0,0,1,0,0], [1,5])
    
    # Run the one cross entropy loss operation
    loss=sess.run(loss_op, feed_dict={input_:x, 
                                      label_ohe: y_ohe
                                      })
    
    # Run the other cross entropy loss operation
    sparse_loss=sess.run(loss_op_sparse, feed_dict={input_:x,
                                                    label: y
                                                    })
    
    print('\n\n\nCross entropy loss: %.2f'%loss)
    print('Sparse cross entropy loss: %.2f'%sparse_loss)




Cross entropy loss: 0.18
Sparse cross entropy loss: 0.18


In [8]:
# Import numpy for some array reshaping
import numpy as np

# Create an empty graph, that will be filled with operation nodes later
main_graph=tf.Graph()

# Register this graph as default graph. 
# All operations within this context will become operation nodes in this graph
with main_graph.as_default():
    
    # Placeholder for data input
    input_=tf.placeholder(dtype=tf.float32, shape=[1,5], name='input')
    # Placeholder for the label
    labels=tf.placeholder(dtype=tf.float32, shape=[1,1], name='labels')

    # Define a 5x1 weight matrix
    W=tf.get_variable(name='weights', shape=[5,1])
    
    # Forward propagation
    forward=tf.nn.tanh(tf.matmul(input_, W))

    # Mean squared error loss function
    loss=tf.losses.mean_squared_error(labels, forward)
    
    # Define the instance of the class that performs the gradient descent step
    optimizer=tf.train.GradientDescentOptimizer(learning_rate=0.1)
    
    # Get all trainable parameters of the network (here: the weight matrix W)
    trainable_variables=tf.trainable_variables()
    
    # Compute the gradients of the loss function with respect to the weights
    gradients= tf.gradients(loss, trainable_variables)
    
    # Perform the gradient descent step.
    # The input argument are tuples. Each tuple is a pair of the gradient and the weight 
    # that was used to calculate this gradient
    update_step=optimizer.apply_gradients(zip(gradients, trainable_variables))
     
    
    #Alternative Solution 
    update_step_alternative=tf.train.GradientDescentOptimizer(learning_rate=0.001).minimize(loss)
       
    
    
# Create a session to execute the dataflow graph   
with tf.Session(graph=main_graph) as sess:
    
    # Initialize the weight matrix
    sess.run(tf.global_variables_initializer())
    
    # Define some random input and a label
    x=np.array([1,1,0,2,5]).reshape([1,5])
    y=np.array([2]).reshape([1,1]) 
    
    # Perform one single gradient descent step
    sess.run(update_step, feed_dict={input_: x,
                                     labels: y
                                     }) 

In [9]:
import numpy as np
from random import shuffle

# list that will contain our training set
training_data=[]

# How many digits should this binary number have?
n=11
    
#Mini-batch size
batch_size=16

print('\n\nGeneration of Data...\n') 
for i in np.arange(2048):
    
    # Create a binary number of type string
    b = bin(i)[2:]
    l = len(b)
    b = str(0) * (n - l) + b  

    # Convert the binary string number to type float
    features=np.array(list(b)).astype(float)
    
    # Create and normalize the corresponding decimal label
    label=float(i)/2047
    
    # Put the feature-label instance into the list
    training_data.append([features, label])
    
    if (i>=1 and i<11) or (i>=2038):
        print('binary number: %s, decimal number: %d' %(b, i))
        
# shuffle the data
shuffle(training_data)  

# convert the list to np.array     
training_data=np.array(training_data)


#%%

# Get the next mini-batch of training samples
def get_next_batch(n_batch):
    
    # Get the next mini-batch of training samples from the dataset
    features=training_data[n_batch*batch_size:(batch_size*(1+n_batch)),0]
    labels=training_data[n_batch*batch_size:(batch_size*(1+n_batch)),1]
    
    # Reshape the list of arrays into a nxn np.array
    features = np.concatenate(features).reshape([batch_size,11])  
    # Reshape the labels 
    labels=np.reshape(labels, [batch_size,1])
    
    return features, labels
    
features, labels=get_next_batch(n_batch=1)

print(features)
print(labels)
#%%  

# Create the training graph
main_graph=tf.Graph()

with main_graph.as_default():
    
    # Define the placeholders for the features and the labels
    x=tf.placeholder(dtype=tf.float32,shape=[batch_size,11], name='features')
    y=tf.placeholder(dtype=tf.float32, shape=[batch_size,1], name='labels')
           
    # Create the weight matrices and the bias vectors 
    initializer=initializer=tf.random_normal_initializer(mean=0.0, stddev=0.25)
   
    W1=tf.get_variable('W1',shape=[11,50], initializer=initializer)
    W2=tf.get_variable('W2',shape=[50,25], initializer=initializer)
    W3=tf.get_variable('W3',shape=[25,1], initializer=initializer)
    
    b1=tf.get_variable('b1',shape=[50], initializer=initializer)
    b2=tf.get_variable('b2',shape=[25], initializer=initializer)

    ### Define the forward propagation step ###
    
    # First hidden layer
    z1=tf.matmul(x,W1)+b1
    a1=tf.nn.tanh(z1)
    
    # Second hidden layer
    z2=tf.matmul(a1,W2)+b2
    a2=tf.nn.tanh(z2)
    
    # Outputlayer
    predict_op=tf.nn.relu(tf.matmul(a2,W3))
    
    # Define the loss function
    loss_op=tf.losses.mean_squared_error(y,predict_op)
       
    # Perform a gradient descent step
    optimizer=tf.train.GradientDescentOptimizer(learning_rate=0.01)
    trainable_parameters = tf.trainable_variables()
    gradients = tf.gradients(loss_op,trainable_parameters)
    update_step = optimizer.apply_gradients(zip(gradients, trainable_parameters))


print('\n\nStart of the training...\n')
with tf.Session(graph=main_graph) as sess:
    
    sess.run(tf.global_variables_initializer())

    # How many mini-batches in total?
    num_batches=int(2048/batch_size)
    
    loss=0

    #Iterate over the entire training set for 10 times
    for epoch in range(10):
            
        # Iterate over the number of mini-batches
        for n_batch in range(num_batches-1):
            
            # Get the next mini-batches of samples for the training set
            features, labels=get_next_batch(n_batch)
              
            # Perform the gradient descent step on that mini-batch and compute the loss value
            _, loss_=sess.run((update_step, loss_op), feed_dict={x:features, y:labels})   
            loss+=loss_
             
        print('epoch_nr.: %i, loss: %.3f' %(epoch,(loss/num_batches)))
        loss=0 

    # Compute the prediction on the last mini-batch
    prediction=sess.run(predict_op, feed_dict={x:features})
    
    # Iterate over the features and labels from the last mini-batch as well as
    # the predicitons made by the network, and compare them to check the performance
    for f, l, p in zip(features, labels, prediction):
        
        # Rescale the predictions and labels back into their original value range
        p=p*2047
        l=l*2047
        
        print('Binary number: %s,  label: %i, prediciton %i' %(str(f), l,p))



Generation of Data...

binary number: 00000000001, decimal number: 1
binary number: 00000000010, decimal number: 2
binary number: 00000000011, decimal number: 3
binary number: 00000000100, decimal number: 4
binary number: 00000000101, decimal number: 5
binary number: 00000000110, decimal number: 6
binary number: 00000000111, decimal number: 7
binary number: 00000001000, decimal number: 8
binary number: 00000001001, decimal number: 9
binary number: 00000001010, decimal number: 10
binary number: 11111110110, decimal number: 2038
binary number: 11111110111, decimal number: 2039
binary number: 11111111000, decimal number: 2040
binary number: 11111111001, decimal number: 2041
binary number: 11111111010, decimal number: 2042
binary number: 11111111011, decimal number: 2043
binary number: 11111111100, decimal number: 2044
binary number: 11111111101, decimal number: 2045
binary number: 11111111110, decimal number: 2046
binary number: 11111111111, decimal number: 2047
[[0. 0. 1. 1. 1. 1. 1. 0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:37: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray


epoch_nr.: 0, loss: 0.223
epoch_nr.: 1, loss: 0.036
epoch_nr.: 2, loss: 0.012
epoch_nr.: 3, loss: 0.009
epoch_nr.: 4, loss: 0.007
epoch_nr.: 5, loss: 0.007
epoch_nr.: 6, loss: 0.006
epoch_nr.: 7, loss: 0.006
epoch_nr.: 8, loss: 0.005
epoch_nr.: 9, loss: 0.005
Binary number: [0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0.],  label: 268, prediciton 84
Binary number: [1. 0. 1. 1. 1. 1. 0. 0. 1. 0. 1.],  label: 1509, prediciton 1672
Binary number: [0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1.],  label: 97, prediciton 0
Binary number: [1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1.],  label: 1807, prediciton 1903
Binary number: [0. 0. 0. 1. 1. 0. 0. 0. 1. 1. 0.],  label: 198, prediciton 176
Binary number: [0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 0.],  label: 726, prediciton 519
Binary number: [0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 1.],  label: 77, prediciton 0
Binary number: [1. 1. 0. 0. 1. 0. 1. 1. 1. 1. 0.],  label: 1630, prediciton 1608
Binary number: [0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1.],  label: 509, prediciton 615
Binary number: [1. 0. 1. 0. 1.

In [10]:
import numpy as np
from random import shuffle

# list that will contain our training set
training_data=[]

# How many digits should this binary number have?
n=4
    
#Mini-batch size
batch_size=8

print('\n\nGeneration of Data...\n') 
for i in np.arange(0, 10):
    
    # Create a binary number of type string
    b = bin(i)[2:]
    l = len(b)
    b = str(0) * (n - l) + b  

    # Convert binary string number to type float
    features=np.array(list(b)).astype(float)
    # Create the corresponding binary label / class
    label=i
    
    # Put the feature-label pair into the list
    training_data.append([features, label])

    print('binary number: %s, decimal number: %d' %(b, i))
        
    
#%%
# shuffle the data
shuffle(training_data)  

training_data=training_data*1000

# convert the list to np.array     
training_data=np.array(training_data)



#%%

# Get the next mini-batch of training samples
def get_next_batch(n_batch):
    
    # Get the next mini-batch of training samples from the dataset
    features=training_data[n_batch*batch_size:(batch_size*(1+n_batch)),0]
    labels=training_data[n_batch*batch_size:(batch_size*(1+n_batch)),1]
    
    # Reshape the list of arrays into a nxn np.array
    features = np.concatenate(features).reshape([batch_size, 4])  
    # Reshape the labels 
    labels=np.reshape(labels, [batch_size])
    
    return features, labels
    
features, labels=get_next_batch(n_batch=1)

print('\n\nMini-batch of features: \n')
print(features)
print('\n\nMini-batch of labels: \n')
print(labels)

#%%  

# Create the training graph
main_graph=tf.Graph()

with main_graph.as_default():
    
    # Define the placeholders for the features and the labels
    x=tf.placeholder(dtype=tf.float32,shape=[batch_size, 4], name='features')
    y=tf.placeholder(dtype=tf.int32, shape=[batch_size], name='labels')
           
    # Create the weight matrices and the bias vectors 
    initializer=initializer=tf.random_normal_initializer(mean=0.0, stddev=0.25)
   
    W1=tf.get_variable('W1',shape=[4,50], initializer=initializer)
    W2=tf.get_variable('W2',shape=[50,25], initializer=initializer)
    W3=tf.get_variable('W3',shape=[25,10], initializer=initializer)
    
    b1=tf.get_variable('b1',shape=[50], initializer=initializer)
    b2=tf.get_variable('b2',shape=[25], initializer=initializer)

    ### Define the forward propagation step ###
    
    # First hidden layer
    z1=tf.matmul(x,W1)+b1
    a1=tf.nn.tanh(z1)
    
    # Second hidden layer
    z2=tf.matmul(a1,W2)+b2
    a2=tf.nn.tanh(z2)
    
    # Outputlayer, without an activation function (input for the loss function)
    logits=tf.matmul(a2,W3)
       
    # Compute the probability scores after the training)
    probs=tf.nn.softmax(logits)
    
    # Define the loss function
    loss_op=tf.losses.sparse_softmax_cross_entropy(labels=y, logits=logits)
       
    # Perform a gradient descent step
    optimizer=tf.train.GradientDescentOptimizer(learning_rate=0.001)
    trainable_parameters = tf.trainable_variables()
    gradients = tf.gradients(loss_op,trainable_parameters)
    update_step = optimizer.apply_gradients(zip(gradients, trainable_parameters))


print('\n\nStart of the training...\n')
with tf.Session(graph=main_graph) as sess:
    
    sess.run(tf.global_variables_initializer())

    # How many mini-batches in total?
    num_batches=int(10000/batch_size)
    
    loss=0

    #Iterate over the entire training set for 10 times
    for epoch in range(10):
            
        # Iterate over the number of mini-batches
        for n_batch in range(num_batches-1):
            
            # Get the next mini-batches of samples for the training set
            features, labels=get_next_batch(n_batch)
              
            # Perform the gradient descent step on that mini-batch and compute the loss value
            _, loss_=sess.run((update_step, loss_op), feed_dict={x:features, y:labels})   
            
            loss+=loss_
             
        print('epoch_nr.: %i, loss: %.3f' %(epoch,(loss/num_batches)))
        loss=0 
    
    
    print('\n\nTesting the neural network:\n')
    # Compute the probability scores for the last mini-batch
    prob_scores=sess.run(probs, feed_dict={x:features, y:labels})
    
    # Iterate over the features and labels from the last mini-batch as well as
    # the predicitons made by the network, and compare them to check the performance
    for f, l, p in zip(features, labels, prob_scores):
    
        # Get the class with the highest probability score
        predicted_class=np.argmax(p)
        # Get the actual probability score
        predicted_class_score=np.max(p)
     
        print('Binary number: %s, decimal number: %i, predicted_class: %i, predicted_prob_score: %.3f' 
              %(str(f), l, predicted_class, predicted_class_score))



Generation of Data...

binary number: 0000, decimal number: 0
binary number: 0001, decimal number: 1
binary number: 0010, decimal number: 2
binary number: 0011, decimal number: 3
binary number: 0100, decimal number: 4
binary number: 0101, decimal number: 5
binary number: 0110, decimal number: 6
binary number: 0111, decimal number: 7
binary number: 1000, decimal number: 8
binary number: 1001, decimal number: 9


Mini-batch of features: 

[[1. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 1. 1. 1.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 1.]
 [0. 0. 1. 0.]
 [0. 1. 1. 0.]]


Mini-batch of labels: 

[9 0 7 1 8 3 2 6]


Start of the training...



/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:39: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray


epoch_nr.: 0, loss: 2.169
epoch_nr.: 1, loss: 1.572
epoch_nr.: 2, loss: 1.182
epoch_nr.: 3, loss: 0.887
epoch_nr.: 4, loss: 0.665
epoch_nr.: 5, loss: 0.503
epoch_nr.: 6, loss: 0.387
epoch_nr.: 7, loss: 0.305
epoch_nr.: 8, loss: 0.247
epoch_nr.: 9, loss: 0.205


Testing the neural network:

Binary number: [0. 0. 1. 0.], decimal number: 2, predicted_class: 2, predicted_prob_score: 0.832
Binary number: [0. 1. 1. 0.], decimal number: 6, predicted_class: 6, predicted_prob_score: 0.787
Binary number: [0. 1. 0. 0.], decimal number: 4, predicted_class: 4, predicted_prob_score: 0.862
Binary number: [0. 1. 0. 1.], decimal number: 5, predicted_class: 5, predicted_prob_score: 0.824
Binary number: [1. 0. 0. 1.], decimal number: 9, predicted_class: 9, predicted_prob_score: 0.870
Binary number: [0. 0. 0. 0.], decimal number: 0, predicted_class: 0, predicted_prob_score: 0.823
Binary number: [0. 1. 1. 1.], decimal number: 7, predicted_class: 7, predicted_prob_score: 0.793
Binary number: [0. 0. 0. 1.], 

In [11]:
import numpy as np
from random import shuffle

# list that will contain our training set
training_data=[]

# How many digits should this binary number have?
n=11
    
#Mini-batch size
batch_size=16

print('\n\nGeneration of Data...\n') 
for i in np.arange(2048):
    
    # Create a binary number of type string
    b = bin(i)[2:]
    l = len(b)
    b = str(0) * (n - l) + b  

    # Convert the binary string number to type float
    features=np.array(list(b)).astype(float)
    
    # Create and normalize the corresponding decimal label
    label=float(i)/2047
    
    # Put the feature-label instance into the list
    training_data.append([features, label])
    
    if (i>=1 and i<11) or (i>=2038):
        print('binary number: %s, decimal number: %d' %(b, i))
        
# shuffle the data
shuffle(training_data)  

# convert the list to np.array     
training_data=np.array(training_data)


#%%

# Get the next mini-batch of training samples
def get_next_batch(n_batch):
    
    # Get the next mini-batch of training samples from the dataset
    features=training_data[n_batch*batch_size:(batch_size*(1+n_batch)),0]
    labels=training_data[n_batch*batch_size:(batch_size*(1+n_batch)),1]
    
    # Reshape the list of arrays into a nxn np.array
    features = np.concatenate(features).reshape([batch_size,11])  
    # Reshape the labels 
    labels=np.reshape(labels, [batch_size,1])
    
    return features, labels
    
features, labels=get_next_batch(n_batch=1)

print(features)
print(labels)
#%%  

# Create the training graph
main_graph=tf.Graph()

with main_graph.as_default():
    
    # Define the placeholders for the features and the labels
    x=tf.placeholder(dtype=tf.float32,shape=[batch_size,11], name='features')
    y=tf.placeholder(dtype=tf.float32, shape=[batch_size,1], name='labels')
           
    # Create the weight matrices and the bias vectors 
    initializer=initializer=tf.random_normal_initializer(mean=0.0, stddev=0.25)
   
    W1=tf.get_variable('W1',shape=[11,50], initializer=initializer)
    W2=tf.get_variable('W2',shape=[50,25], initializer=initializer)
    W3=tf.get_variable('W3',shape=[25,1], initializer=initializer)
    
    b1=tf.get_variable('b1',shape=[50], initializer=initializer)
    b2=tf.get_variable('b2',shape=[25], initializer=initializer)

    ### Define the forward propagation step with Dropout ###
    
    z1=tf.matmul(x,W1)+b1
    a1=tf.nn.tanh(z1)
    a1_dropout= tf.nn.dropout(a1, rate=0.25)
    
    z2=tf.matmul(a1_dropout,W2)+b2
    a2=tf.nn.tanh(z2)
    a2_dropout= tf.nn.dropout(a2, rate=0.25)
    
    # Outputlayer
    predict_op=tf.nn.relu(tf.matmul(a2_dropout,W3))
    
    # Define the loss function
    loss_op=tf.losses.mean_squared_error(y,predict_op)
       
    # Perform a gradient descent step
    optimizer=tf.train.GradientDescentOptimizer(learning_rate=0.01)
    trainable_parameters = tf.trainable_variables()
    gradients = tf.gradients(loss_op,trainable_parameters)
    update_step = optimizer.apply_gradients(zip(gradients, trainable_parameters))


print('\n\nStart of the training...\n')
with tf.Session(graph=main_graph) as sess:
    
    sess.run(tf.global_variables_initializer())

    # How many mini-batches in total?
    num_batches=int(2048/batch_size)
    
    loss=0

    #Iterate over the entire training set for 10 times
    for epoch in range(10):
            
        # Iterate over the number of mini-batches
        for n_batch in range(num_batches-1):
            
            # Get the next mini-batches of samples for the training set
            features, labels=get_next_batch(n_batch)
              
            # Perform the gradient descent step on that mini-batch and compute the loss value
            _, loss_=sess.run((update_step, loss_op), feed_dict={x:features, y:labels})   
            loss+=loss_
             
        print('epoch_nr.: %i, loss: %.3f' %(epoch,(loss/num_batches)))
        loss=0 

    # Compute the prediction on the last mini-batch
    prediction=sess.run(predict_op, feed_dict={x:features})
    
    # Iterate over the features and labels from the last mini-batch as well as
    # the predicitons made by the network, and compare them to check the performance
    for f, l, p in zip(features, labels, prediction):
        
        # Rescale the predictions and labels back into their original value range
        p=p*2047
        l=l*2047
        
        print('Binary number: %s,  label: %i, prediciton %i' %(str(f), l,p))



Generation of Data...

binary number: 00000000001, decimal number: 1
binary number: 00000000010, decimal number: 2
binary number: 00000000011, decimal number: 3
binary number: 00000000100, decimal number: 4
binary number: 00000000101, decimal number: 5
binary number: 00000000110, decimal number: 6
binary number: 00000000111, decimal number: 7
binary number: 00000001000, decimal number: 8
binary number: 00000001001, decimal number: 9
binary number: 00000001010, decimal number: 10
binary number: 11111110110, decimal number: 2038
binary number: 11111110111, decimal number: 2039
binary number: 11111111000, decimal number: 2040
binary number: 11111111001, decimal number: 2041
binary number: 11111111010, decimal number: 2042
binary number: 11111111011, decimal number: 2043
binary number: 11111111100, decimal number: 2044
binary number: 11111111101, decimal number: 2045
binary number: 11111111110, decimal number: 2046
binary number: 11111111111, decimal number: 2047
[[0. 0. 1. 1. 0. 1. 1. 1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:37: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray


epoch_nr.: 0, loss: 0.284
epoch_nr.: 1, loss: 0.178
epoch_nr.: 2, loss: 0.118
epoch_nr.: 3, loss: 0.073
epoch_nr.: 4, loss: 0.055
epoch_nr.: 5, loss: 0.044
epoch_nr.: 6, loss: 0.037
epoch_nr.: 7, loss: 0.034
epoch_nr.: 8, loss: 0.033
epoch_nr.: 9, loss: 0.031
Binary number: [0. 1. 1. 1. 1. 0. 0. 1. 1. 1. 0.],  label: 974, prediciton 553
Binary number: [0. 0. 1. 1. 1. 0. 1. 0. 1. 0. 0.],  label: 468, prediciton 313
Binary number: [1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 1.],  label: 1283, prediciton 687
Binary number: [0. 0. 1. 1. 0. 1. 0. 1. 1. 1. 0.],  label: 430, prediciton 432
Binary number: [1. 0. 1. 0. 0. 1. 1. 1. 0. 0. 1.],  label: 1337, prediciton 1455
Binary number: [0. 0. 1. 1. 0. 1. 1. 1. 1. 0. 1.],  label: 445, prediciton 73
Binary number: [1. 1. 0. 1. 1. 1. 1. 1. 0. 0. 1.],  label: 1785, prediciton 948
Binary number: [0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0.],  label: 288, prediciton 0
Binary number: [1. 0. 0. 1. 1. 1. 1. 0. 0. 1. 0.],  label: 1266, prediciton 1691
Binary number: [0. 1. 0. 0

In [12]:
import numpy as np
from random import shuffle

# list that will contain our training set
training_data=[]

# How many digits should this binary number have?
n=11
    
#Mini-batch size
batch_size=16

print('\n\nGeneration of Data...\n') 
for i in np.arange(2048):
    
    # Create a binary number of type string
    b = bin(i)[2:]
    l = len(b)
    b = str(0) * (n - l) + b  

    # Convert the binary string number to type float
    features=np.array(list(b)).astype(float)
    
    # Create and normalize the corresponding decimal label
    label=float(i)/2047
    
    # Put the feature-label instance into the list
    training_data.append([features, label])
    
    if (i>=1 and i<11) or (i>=2038):
        print('binary number: %s, decimal number: %d' %(b, i))
        
# shuffle the data
shuffle(training_data)  

# convert the list to np.array     
training_data=np.array(training_data)


#%%

# Get the next mini-batch of training samples
def get_next_batch(n_batch):
    
    # Get the next mini-batch of training samples from the dataset
    features=training_data[n_batch*batch_size:(batch_size*(1+n_batch)),0]
    labels=training_data[n_batch*batch_size:(batch_size*(1+n_batch)),1]
    
    # Reshape the list of arrays into a nxn np.array
    features = np.concatenate(features).reshape([batch_size,11])  
    # Reshape the labels 
    labels=np.reshape(labels, [batch_size,1])
    
    return features, labels
    
features, labels=get_next_batch(n_batch=1)

print(features)
print(labels)
#%%  

# Create the training graph
main_graph=tf.Graph()

with main_graph.as_default():
    
    # Define the placeholders for the features and the labels
    x=tf.placeholder(dtype=tf.float32,shape=[batch_size,11], name='features')
    y=tf.placeholder(dtype=tf.float32, shape=[batch_size,1], name='labels')
           
    # Create the weight matrices and the bias vectors 
    initializer=initializer=tf.random_normal_initializer(mean=0.0, stddev=0.25)
   
    W1=tf.get_variable('W1',shape=[11,50], initializer=initializer)
    W2=tf.get_variable('W2',shape=[50,25], initializer=initializer)
    W3=tf.get_variable('W3',shape=[25,1], initializer=initializer)
    
    b1=tf.get_variable('b1',shape=[50], initializer=initializer)
    b2=tf.get_variable('b2',shape=[25], initializer=initializer)

    ### Define the forward propagation step ###
    
    # First hidden layer
    z1=tf.matmul(x,W1)+b1
    a1=tf.nn.tanh(z1)
    
    # Second hidden layer
    z2=tf.matmul(a1,W2)+b2
    a2=tf.nn.tanh(z2)
    
    # Outputlayer
    predict_op=tf.nn.relu(tf.matmul(a2,W3))
    
	
	
	#### L2-Regularization ####
	
	# Collect the weight matrices
    weight_matrices=[var for var in tf.trainable_variables() if 'bias' not in var.name] 
	#Apply the L2 regularization to the weight matrices
    l2_losses=[tf.nn.l2_loss(w) for w in weight_matrices]
    l2_loss = tf.add_n(l2_losses)
    
	# Regularization rate
    alpha=0.1
    
	# Add the L2 regularization to the regular loss function
    loss_op=tf.losses.mean_squared_error(y,predict_op)+alpha*l2_loss
	
	########
       
    # Perform a gradient descent step
    optimizer=tf.train.GradientDescentOptimizer(learning_rate=0.01)
    trainable_parameters = tf.trainable_variables()
    gradients = tf.gradients(loss_op,trainable_parameters)
    update_step = optimizer.apply_gradients(zip(gradients, trainable_parameters))


print('\n\nStart of the training...\n')
with tf.Session(graph=main_graph) as sess:
    
    sess.run(tf.global_variables_initializer())

    # How many mini-batches in total?
    num_batches=int(2048/batch_size)
    
    loss=0

    #Iterate over the entire training set for 10 times
    for epoch in range(10):
            
        # Iterate over the number of mini-batches
        for n_batch in range(num_batches-1):
            
            # Get the next mini-batches of samples for the training set
            features, labels=get_next_batch(n_batch)
              
            # Perform the gradient descent step on that mini-batch and compute the loss value
            _, loss_=sess.run((update_step, loss_op), feed_dict={x:features, y:labels})   
            loss+=loss_
             
        print('epoch_nr.: %i, loss: %.3f' %(epoch,(loss/num_batches)))
        loss=0 

    # Compute the prediction on the last mini-batch
    prediction=sess.run(predict_op, feed_dict={x:features})
    
    # Iterate over the features and labels from the last mini-batch as well as
    # the predicitons made by the network, and compare them to check the performance
    for f, l, p in zip(features, labels, prediction):
        
        # Rescale the predictions and labels back into their original value range
        p=p*2047
        l=l*2047
        
        print('Binary number: %s,  label: %i, prediciton %i' %(str(f), l,p))



Generation of Data...

binary number: 00000000001, decimal number: 1
binary number: 00000000010, decimal number: 2
binary number: 00000000011, decimal number: 3
binary number: 00000000100, decimal number: 4
binary number: 00000000101, decimal number: 5
binary number: 00000000110, decimal number: 6
binary number: 00000000111, decimal number: 7
binary number: 00000001000, decimal number: 8
binary number: 00000001001, decimal number: 9
binary number: 00000001010, decimal number: 10
binary number: 11111110110, decimal number: 2038
binary number: 11111110111, decimal number: 2039
binary number: 11111111000, decimal number: 2040
binary number: 11111111001, decimal number: 2041
binary number: 11111111010, decimal number: 2042
binary number: 11111111011, decimal number: 2043
binary number: 11111111100, decimal number: 2044
binary number: 11111111101, decimal number: 2045
binary number: 11111111110, decimal number: 2046
binary number: 11111111111, decimal number: 2047
[[1. 1. 0. 0. 1. 0. 0. 1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:37: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray


epoch_nr.: 0, loss: 5.243
epoch_nr.: 1, loss: 3.962
epoch_nr.: 2, loss: 3.070
epoch_nr.: 3, loss: 2.387
epoch_nr.: 4, loss: 1.861
epoch_nr.: 5, loss: 1.456
epoch_nr.: 6, loss: 1.144
epoch_nr.: 7, loss: 0.903
epoch_nr.: 8, loss: 0.718
epoch_nr.: 9, loss: 0.575
Binary number: [0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1.],  label: 991, prediciton 1032
Binary number: [1. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0.],  label: 1816, prediciton 1507
Binary number: [1. 1. 1. 1. 1. 0. 1. 1. 0. 0. 1.],  label: 2009, prediciton 1601
Binary number: [1. 1. 0. 0. 1. 1. 0. 0. 0. 1. 1.],  label: 1635, prediciton 1383
Binary number: [1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0.],  label: 1982, prediciton 1669
Binary number: [0. 1. 1. 1. 0. 0. 0. 1. 0. 0. 1.],  label: 905, prediciton 947
Binary number: [1. 0. 0. 1. 1. 1. 1. 0. 1. 0. 1.],  label: 1269, prediciton 1145
Binary number: [0. 1. 0. 0. 1. 1. 0. 1. 1. 1. 0.],  label: 622, prediciton 788
Binary number: [1. 0. 0. 0. 1. 1. 1. 1. 0. 1. 1.],  label: 1147, prediciton 1087
Binary number: [